export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL = 500,
  SERVICE_UNAVAILABLE = 503,
}

export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  AUTH_SERVICE_UNAVAILABLE = 'AUTH_SERVICE_UNAVAILABLE',
}
